### PR TITLE
:bug: Fixed #159.

### LINKED ISSUE #159: The score percentage won't be added when adding new question to an exam.
image

image

### PR DESCRIPTION
**Pull request by nyngwang**
Resolved issue 159.

image

### CODE REVIEW

File: src/models/Question.js [hunk 1]
```diff
@@ -1,9 +1,9 @@
 export default class Question {
-    constructor({examId, problemId, quota, maxScore, questionOrder}) {
+    constructor({examId, problemId, quota, score, questionOrder}) {
         this.examId = examId;
         this.problemId = problemId;
         this.quota = quota;
-        this.maxScore = maxScore;
+        this.score = score;
         this.questionOrder = questionOrder;
     }
```
Comment (Johnny850807) [inline src/models/Question.js:8]: Please make sure this won't break

**Review by Johnny850807 — CHANGES_REQUESTED** [review]
Review done
